spring:
  datasource:
    url : jdbc:oracle:thin:@//localhost:1521/orcl
    username : pharmacy
    password : pharmacy  
    jpa :
       database-platform: org.hibernate.dialect.Oracle10gDialect
       show-sql : true
       generate-ddl : false
       hibernate :
       ddl-auto : update   
test:
  name: jagadish
  location: testlabel    
